# Generated by Django 3.0.6 on 2020-06-06 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la course')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la course')),
                ('city', models.CharField(max_length=100, verbose_name='ville de la course')),
                ('address', models.CharField(max_length=100, verbose_name='Lieu du départ de la course')),
            ],
            options={
                'verbose_name': 'Course',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Type de course',
            },
        ),
    ]
