# Generated by Django 3.0.6 on 2020-06-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resultats.RaceType'),
        ),
    ]
