# Generated by Django 3.0.6 on 2020-06-07 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0003_runner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resultats.Race')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resultats.Runner')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='runners',
            field=models.ManyToManyField(through='resultats.RunnerRace', to='resultats.Runner'),
        ),
    ]
