# Generated by Django 3.0.6 on 2020-06-07 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0004_auto_20200607_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runnerrace',
            name='favorite',
        ),
        migrations.AddField(
            model_name='runnerrace',
            name='indications',
            field=models.CharField(max_length=100, null=True, verbose_name='Indications spécifique du médécin'),
        ),
        migrations.AddField(
            model_name='runnerrace',
            name='registerDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'Inscription à la course"),
        ),
        migrations.AddField(
            model_name='runnerrace',
            name='time',
            field=models.FloatField(default=0, verbose_name='temps de course pour ce coureur'),
        ),
    ]
