# Generated by Django 3.0.6 on 2020-06-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0006_auto_20200607_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerrace',
            name='indications',
            field=models.TextField(max_length=100, null=True, verbose_name='Indications spécifiques du médécin'),
        ),
        migrations.AlterUniqueTogether(
            name='runnerrace',
            unique_together={('runner', 'race')},
        ),
    ]
