# Generated by Django 3.0.6 on 2020-06-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0010_auto_20200607_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerrace',
            name='bibNumber',
            field=models.IntegerField(default=0, verbose_name='Numéro de dossard du coureur'),
        ),
    ]
